name: 'Release'
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_FOLDER: build
      PLUGIN_SLUG: fix-wp-unzip

    steps:
      - name: Setup PHP with WP-CLI.
        uses: shivammathur/setup-php@v2
        with:
          tools: wp
          php-version: 8.2

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.BUILD_FOLDER }}
          ref: ${{ github.ref }}

      - name: Configure WP-CLI dist-archive-command
        run: |
          wp package install wp-cli/dist-archive-command

      - name: Build Plugin Zip
        run: |
          wp dist-archive ${{ env.BUILD_FOLDER }} --plugin-dirname=${{ env.PLUGIN_SLUG }}

      - name: Save to Release
        uses: xresloader/upload-to-github-release@v1
        if: ${{ github.event.release.prerelease == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.zip"
          tags: true
